#!/usr/bin/env python
from boto.route53.record import ResourceRecordSets
import boto.ec2
import boto.route53

ec2_conn = boto.ec2.connect_to_region("us-west-2")
active_ips = [r.instances[0].ip_address for r in ec2_conn.get_all_reservations()]

r53_conn = boto.route53.connect_to_region("us-west-2")
zone = r53_conn.get_zone('ambulnz-dev.com')
zone_records = [z for z in zone.get_records() if z.name.startswith('am-')]

dead = [r for r in zone_records if r.resource_records[0] not in active_ips] 

print 'Deleting ' + str(len(dead)) + ' unused DNS entries.'
changes = ResourceRecordSets(r53_conn, zone.id)

for d in dead:
  print d

print dir(dead[0])
